name: "Write Summary"
description: "GitHub ActionsのSummaryを書く"
inputs:
  message:
    description: "What to write in the summary"
    required: true
runs:
  using: "composite"
  steps:
    - name: Write Summary
      uses: actions/github-script@v7.0.1
      env:
        INPUT_MESSAGE: ${{ inputs.message }}
      with:
        script: |
          const message = process.env.INPUT_MESSAGE;
          core.summary.addRaw(message, true);
          core.summary.write();
          core.setFailed(message);