name: "Write Summary"
description: "GitHub ActionsのSummaryを書く"
inputs:
  message:
    description: "What to write in the summary"
    required: false
runs:
  using: "composite"
  steps:
    - name: Write Summary
      uses: actions/github-script@v7.0.1
      env:
        INPUT_MESSAGE: ${{ inputs.message }}
      with:
        script: |
          const message = process.env.INPUT_MESSAGE;
          const fs = require('fs');
          if (!message) {
            fs.readFile('summary.md', 'utf8', (err, data) => {
              if (err) {
                core.setFailed(err.message);
              }
              core.setOutput('summary', data);
            });
          }
          core.summary.addRaw(message, true);
          core.summary.write();
          core.setFailed(message);