name: Next.js Build Check
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install Bun
        run: npm install -g bun
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build