name: Show Vercel Deploy Log
on:
  workflow_dispatch:
    inputs:
      vercel-deploy-url:
        description: 'Vercel Deploy URL'
        required: true
jobs:
  show-deploy-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Link Vercel Project
        run: vercel link --token=${{secrets.VERCEL_TOKEN}} --project ${{vars.VERCEL_PROJECT}} --yes
      - name: Get Vercel Deploy Log
        run: |
          vercel inspect ${{ github.event.inputs.vercel-deploy-url }} --logs --token=${{secrets.VERCEL_TOKEN}} > deploy-log.txt || echo "Failed to fetch logs." > deploy-log.txt
        continue-on-error: true     
      - name: Create Summary File
        id: create-summary
        run: |
          echo "## :rocket: Vercel Deploy Log" > summary.md
          echo '```' >> summary.md
          cat deploy-log.txt >> summary.md
          echo '```' >> summary.md 

          echo summary="## :rocket: Vercel Deploy Log\n\`\`\`\n$(cat deploy-log.txt)\n\`\`\`" >> $GITHUB_ENV
      - name: Write a summary
        uses: ./.github/actions/write-summary
        with:
          message: ${{ env.summary }}
