name: Show Vercel Deploy Log
on:
  workflow_dispatch:
    inputs:
      vercel-deploy-url:
        description: 'Vercel Deploy URL'
        required: true
jobs:
  show-deploy-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Link Vercel Project
        run: vercel link --token=${{secrets.VERCEL_TOKEN}} --project ${{vars.VERCEL_PROJECT}} --yes
      - name: Get Vercel Deploy Log
        run: |
          vercel inspect ${{ github.event.inputs.vercel-deploy-url }} --logs --token=${{secrets.VERCEL_TOKEN}} > deploy-log.txt 2> deploy-log.txt
        continue-on-error: true
      - name: Insert Deploy Log
        id: insert-deploy-log
        run: echo deploy_log=$(cat deploy-log.txt) >> $GITHUB_ENV
      - name: Show Deploy Log
        run: cat deploy-log.txt
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## 🚀 Vercel Deploy Log
            \`\`\`
            ${process.env.deploy_log}
            \`\`\`
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            await core.summary
              .addRaw(output)
              .write();