name: Vercel Production Deployment
on:
  push:
    branches:
      - main
jobs:
    deployment:
        runs-on: ubuntu-latest
        concurrency: Production
        environment:
            name: Production
            url: ${{ steps.get_release_url.outputs.release_url }}
        steps:
        - uses: actions/checkout@v4
        - name: Deploy to Vercel
          uses: yuito-it/GitHub-Vercel-Actions@v1.0.1
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
            vercel-project: ${{vars.VERCEL_PROJECT }}
        - name: Set release url
          id: get_release_url
          run: echo release_url=$(cat deployment-url.txt) >> $GITHUB_OUTPUT